mybatis:
  #实体类所做包
  type-aliases-package: com.ekold
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

#显示sql
logging:
  level:
    com.ekold.mapper: debug

#缓存
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml